### PR TITLE
Test on PHP 7.3 and 7.4

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Review by nunomaduro — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Ping. :)

**Comment by nunomaduro** [comment]
@JakubOnderka If you don't have time for this project, do not hesitate on give me permissions to handle this kind of trivial pull requests. 👍

**Comment by GrahamCampbell** [comment]
Ping

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by nunomaduro** [comment]
Ping.

**Pull request closed without merging**
