### PR TITLE
Convert to psr-4

### PR DESCRIPTION
**Pull request by avindra**
Directories have been simplified to just src/ and test/

The Test bootstrap file is no longer needed, and the typo in the test
filename has been fixed.

### CODE REVIEW

**Comment by avindra** [comment]
@JakubOnderka : Can you take a look at this one too?

**Comment by avindra** [comment]
@JakubOnderka 

sempai-shark

**Comment by glensc** [comment]
@avindra what's the purpose? it's not outlined in PR and it's not obvious why it is necessary. composer supports psr-0 now and likely indefinitely.

**Comment by avindra** [comment]
[PSR-0 is deprecated](http://www.php-fig.org/psr/psr-0/)

Composer may support it indefinitely (although technically  deprecation should give way to removal), but PHP devs are recommended to use PSR-4 going forward.

**Comment by avindra** [comment]
Additionally, PSR-4 leads to better developer experience (no need to regenerate classmaps during development), and it is cleaner. Just makes sense to use it.

**Comment by glensc** [comment]
that's what you should had put to PR description in first place! :)

**Comment by avindra** [comment]
@JakubOnderka any chance of merging this?

**Pull request merged**
