### PR TITLE
Visual improvements

### PR DESCRIPTION
**Pull request by alecrabbit**
I've extracted some constants, added few methods
Outputs now look better

### CODE REVIEW

**Comment by alecrabbit** [comment]
Screenshot from 2019-04-01 18-49-06

**Comment by alecrabbit** [comment]
@JakubOnderka :wink:

**Comment by GrahamCampbell** [comment]
This repo is now abandoned.

**Comment by nunomaduro** [comment]
You can commit this changes to Collision repository directly

**Comment by alecrabbit** [comment]
> You can commit this changes to Collision repository directly

I'll try to look into it

**Comment by alecrabbit** [comment]
Made a pull request directly to Collision

**Pull request closed without merging**
